// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZFtXX3HxugOibLyD-cYeEk57qs64o_RM',
    appId: '1:975990056168:web:c61b709788fcfb58ef555d',
    messagingSenderId: '975990056168',
    projectId: 'onthespot-d5f33',
    authDomain: 'onthespot-d5f33.firebaseapp.com',
    storageBucket: 'onthespot-d5f33.appspot.com',
    measurementId: 'G-TZ99SC1TQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqe9l4qaYu7ltp-eki1mm92EPbJbsx1j4',
    appId: '1:975990056168:android:ffd2ef7e8d2e027fef555d',
    messagingSenderId: '975990056168',
    projectId: 'onthespot-d5f33',
    storageBucket: 'onthespot-d5f33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Q8q6A3syV5zyX-aB8UbTEsEvvXHuujU',
    appId: '1:975990056168:ios:7fa985ddd261481cef555d',
    messagingSenderId: '975990056168',
    projectId: 'onthespot-d5f33',
    storageBucket: 'onthespot-d5f33.appspot.com',
    iosBundleId: 'com.example.onTheSpot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9Q8q6A3syV5zyX-aB8UbTEsEvvXHuujU',
    appId: '1:975990056168:ios:6b3ed0e247acc316ef555d',
    messagingSenderId: '975990056168',
    projectId: 'onthespot-d5f33',
    storageBucket: 'onthespot-d5f33.appspot.com',
    iosBundleId: 'com.example.onTheSpot.RunnerTests',
  );
}
